### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by rottencandy** [xem/emoji#2]
Thanks for making this!

I tried to use this in a page, but I kept getting a CORS error when I used `src: url(//xem.github.io/unicode13/Twemoji.ttf)`.

I had to add https to the url to make it work `src: url(https://xem.github.io/unicode13/Twemoji.ttf)`.

**Comment by xem** [comment]
ah! this problem shouldn't happen on https domains, does it?

**Comment by rottencandy** [comment]
Seems like it.

Also noticed that the correct font doesn't show up on first page load, but works fine after a refresh. But this happens only on Chrome.

**Comment by rottencandy** [comment]
Update: Looks like I was just drawing them too quickly before they finish loading.
I added a timeout delay to my mainloop, and now it works fine.

**Comment by xem** [comment]
awesome!
